
local MapEvent = {}

MapEvent = {

	MAP_PREPARE_PLAY        = "MAP_PREPARE_START",
	MAP_START_PLAY          = "MAP_START_PLAY",
	MAP_STOP_PLAY           = "MAP_STOP_PLAY",
	MAP_PAUSE_PLAY          = "MAP_PAUSE_PLAY",
	MAP_RESUME_PLAY         = "MAP_RESUMT_PLAY",
	MAP_TIME                = "MAP_TIME",

	OBJECT_ENTER_RANGE      = "OBJECT_ENTER_RANGE",
	OBJECT_EXIT_RANGE       = "OBJECT_EXIT_RANGE",
	OBJECT_IN_RANGE         = "OBJECT_IN_RANGE",
	OBJECT_COLLISION_BEGAN  = "OBJECT_COLLISION_BEGAN",
	OBJECT_COLLISION_ENDED  = "OBJECT_COLLISION_ENDED",
	OBJECT_DESTROY          = "OBJECT_DESTROY",

}

return MapEvent
